import React from "react";
import { LucideCheckSquare } from "lucide-react";
export default function App(){
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <div className="mx-auto max-w-3xl p-6">
        <header className="py-8">
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <LucideCheckSquare className="w-7 h-7" />
            App Starter
          </h1>
          <p className="mt-2 text-slate-600">React + Tailwind scaffold. The generator/LLM will expand this.</p>
        </header>
        <main className="space-y-6">
          <section className="p-6 rounded-lg border bg-slate-50">
            <h2 className="text-xl font-semibold">Getting Started</h2>
            <p className="mt-2 text-slate-600">Add components and logic. This content ensures the site is never blank.</p>
          </section>
        </main>
        <footer className="mt-12 text-sm text-slate-500">Generated by WebAppGenerator</footer>
      </div>
    </div>
  );
}
